name: katayuno_octubre_2014_iteracion_1
author: rchavarria
description: Solucion de la iteración 1 del Katayuno de octubre de 2014
homepage: http://rchavarria.github.io
dev_dependencies:
  unittest: '>=0.10.0'
